Fix macro string interpolation (#225)
I ran into this when upgrading to lucky 0.17. Not yet having made the necessary changes switching forms to operations, I got the unwieldly
```
Error: undefined macro variable 'type'
```

This is due to mistakenly using normal string interpolation where we instead want the macro argument to be interpolated into the error message. This then shows the proper error message

```
Error: BaseForm has been renamed to SaveOperation. Please inherit from Post::SaveOperation.
```